[package]
name = "pistachio"
version = "0.1.0"
license = "GPL-3.0"
edition = "2021"
build = "build.rs"
workspace = ".."
readme = "../README.md"

[dependencies]
ahash = { version = "0.8", optional = true }
lalrpop-util = { version = "0.19", features = [] }
pistachio-macros = { version = "0.1", optional = true, path = "../pistachio-macros" }
serde = "1.0.152"
serde_closure = "0.3.3"
serde_json = { version = "1", optional = true }

[build-dependencies]
lalrpop = { version = "0.19", default-features = false }

[dev-dependencies]
quickcheck = "1"
quickcheck_macros = "1"

[features]
default = ["ahash", "macros", "serde_json", "trace"]

ahash = ["dep:ahash"]
macros = ["dep:pistachio-macros"]
serde_json = ["dep:serde_json"]
trace = []
