[package]
name = "pistachio"
version = "0.1.0"
license = "GPL-3.0"
edition = "2021"
build = "build.rs"
workspace = ".."
readme = "../README.md"

[dependencies]
ahash = { version = "0.8", optional = true }
itoa = "1.0.5"
lalrpop-util = { version = "0.19", default-features = false }
pistachio-macros = { version = "0.1", optional = true, path = "../pistachio-macros" }
ryu = "1.0.12"
serde = "1.0.152"
serde_json = { version = "1", optional = true, default-features = false, features = ["std"] }

[build-dependencies]
lalrpop = { version = "0.19", default-features = false }

[dev-dependencies]
quickcheck = "1"
quickcheck_macros = "1"

[features]
default = ["ahash", "macros", "serde_json", "trace"]

ahash = ["dep:ahash"]
macros = ["dep:pistachio-macros"]
serde_json = ["dep:serde_json"]
trace = []
