[package]
name = "pistachio-macros"
version = "0.1.0"
license = "GPL-3.0"
edition = "2021"
workspace = ".."
readme = "../README.md"

[lib]
proc-macro = true

[dependencies]
bae = "0.1.7"
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
